# Example Helm values.yaml
frontend:
  repository: my-app/frontend
  tag:       # <- you want to change this value
    LOGSTASH_HOST: foo
    ELASTIC_APM_ENABLED: 'true'
backend:
  repository: my-app/backend
  tag: 1.1.0                                # <- and this one
  env:
  - name: TEST
    value: bar6 # <- and this one in a list, selected via sibling value 'TEST'
  - name: BAR
    value: boo
