# Example Helm values.yaml
frontend:
  repository: my-app/frontend
  tag: 2.1.0 # <- you want to change this value
backend:
  repository: my-app/backend
  tag: 2.1.0 # <- and this one
  env:
  - name: TEST
    value: b22dar # <- and this one in a list, selected via sibling value 'TEST'
  - name: BAR
    value: boo
