# Example Helm values.yaml
frontend:
  repository: my-app/frontend
  tag:       # <- you want to change this value
    LOGSTASH_HOST: foo
    ELASTIC_APM_ENABLED: 'true'
backend:
  repository: my-app/backend
  tag: {foo: 1, bar: 2}                     # <- and this one
  env:
  - name: TEST
    value: b22dar # <- and this one in a list, selected via sibling value 'TEST'
  - name: BAR
    value: boo
